version: '3.8'

services:
  client:
    build:
      context: ./onboarding-frontend
    container_name: onboarding_client
    ports:
      - "3002:80"
    environment:
      - VITE_IDENTITY_API_URL=http://localhost:5233/api
      - VITE_CONTENT_API_URL=http://localhost:5233/api
      - VITE_PROGRESS_API_URL=http://localhost:5233/api
    networks:
      - onboarding_net

  mailhog:
    image: mailhog/mailhog
    container_name: onboarding_mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - onboarding_net


networks:
  onboarding_net:
    driver: bridge
