// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingSystem.Data;

#nullable disable

namespace OnboardingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225121504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnboardingSystem.Entities.ActionLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__ActionLo__5E5499A8B7BEDF7C");

                    b.HasIndex("UserId");

                    b.ToTable("ActionLog", (string)null);
                });

            modelBuilder.Entity("OnboardingSystem.Entities.AnswerOption", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnswerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    b.HasKey("AnswerId")
                        .HasName("PK__AnswerOp__D482502408F6A591");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ExternalID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCD767D3C89");

                    b.HasIndex(new[] { "Name" }, "UQ__Departme__737584F630BC325D")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int>("PassingScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(80);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ModuleId")
                        .HasName("PK__Modules__2B747787B4D47241");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06F8C277F87A3");

                    b.HasIndex("ModuleId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A04F18E8C");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B616047850BFA")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.TestAttempt", b =>
                {
                    b.Property<long>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AttemptID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttemptId"));

                    b.Property<DateTime>("AttemptDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AttemptId")
                        .HasName("PK__TestAtte__891A68868F130401");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ExternalID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("MentorID");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Не начат");

                    b.Property<DateTime?>("RimsLastSyncDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("RimsLastSyncDate");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC41930BCF");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MentorId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534CAA8D9F8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.UserModuleProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Не начат");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ProgressId")
                        .HasName("PK__UserModu__BAE29C85994BA69E");

                    b.HasIndex("ModuleId");

                    b.HasIndex(new[] { "UserId", "ModuleId" }, "UQ__UserModu__753F8BD5DAF2E324")
                        .IsUnique();

                    b.ToTable("UserModuleProgress", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF27604F7D17785F");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("OnboardingSystem.Entities.ActionLog", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.User", "User")
                        .WithMany("ActionLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ActionLog_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.AnswerOption", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerOptions_Questions");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Module", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.Department", "Department")
                        .WithMany("Modules")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Modules_Departments");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Question", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.Module", "Module")
                        .WithMany("Questions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Modules");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.TestAttempt", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.Module", "Module")
                        .WithMany("TestAttempts")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestAttempts_Modules");

                    b.HasOne("OnboardingSystem.Entities.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestAttempts_Users");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.User", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Departments");

                    b.HasOne("OnboardingSystem.Entities.User", "Mentor")
                        .WithMany("InverseMentor")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK_Users_Mentor");

                    b.Navigation("Department");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.UserModuleProgress", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.Module", "Module")
                        .WithMany("UserModuleProgresses")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserModuleProgress_Modules");

                    b.HasOne("OnboardingSystem.Entities.User", "User")
                        .WithMany("UserModuleProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserModuleProgress_Users");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("OnboardingSystem.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("OnboardingSystem.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Department", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Module", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestAttempts");

                    b.Navigation("UserModuleProgresses");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("OnboardingSystem.Entities.User", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("InverseMentor");

                    b.Navigation("TestAttempts");

                    b.Navigation("UserModuleProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
